name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted   # runs directly on your Ubuntu server
    steps:
      - name: Run deploy script
        run: bash /home/vid/Documents/Portfolio-2.o/deploy.sh
